--deleting all rows
DELETE FROM ORGANIZATION; 
DELETE FROM HOTEL;
DELETE FROM CONFERENCE;
DELETE FROM ATTENDEE;

--deleting all tables
DROP TABLE ORGANIZATION;
DROP TABLE HOTEL;
DROP TABLE CONFERENCE;
DROP TABLE ATTENDEE;
