CREATE TABLE ORGANIZATION
	(
	  OName NVARCHAR(255) NOT NULL,
	  OAddress NVARCHAR(255) NOT NULL,
	  OCity NVARCHAR(255) NOT NULL,
	  OState NVARCHAR(14) NOT NULL,
	  OZip INT NOT NULL,
	  OEmail NVARCHAR(255) NOT NULL,
	  OPhone CHAR(10) NOT NULL,
	  OID INT NOT NULL,
	  PRIMARY KEY (OID)
	);
	CREATE TABLE HOTEL
	(
	  HMaxMeetSize NVARCHAR(255) NOT NULL,
	  HName NVARCHAR(255) NOT NULL,
	  HState NVARCHAR(255) NOT NULL,
	  HZip INT NOT NULL,
	  HAddress NVARCHAR(255) NOT NULL,
	  HContactPhone INT NOT NULL,
	  HPhone INT NOT NULL,
	  HNumRooms INT NOT NULL,
	  HCity NVARCHAR(255) NOT NULL,
	  PRIMARY KEY (HName)
	);
	CREATE TABLE CONFERENCE
	(
	  CName NVARCHAR(255) NOT NULL,
	  CID INT NOT NULL,
	  CStartDate DATE NOT NULL,
	  CEndDate DATE NOT NULL,
	  CCity NVARCHAR(255) NOT NULL,
	  CFee INT NOT NULL,
	  CAttendance INT NOT NULL,
	  CBudget FLOAT NOT NULL,
	  OID INT NOT NULL,
	  HName NVARCHAR(255) NOT NULL,
	  PRIMARY KEY (CID),
	  FOREIGN KEY (OID) REFERENCES ORGANIZATION(OID),
	  FOREIGN KEY (HName) REFERENCES HOTEL(HName)
	);
	CREATE TABLE ATTENDEE
	(
	  AName NVARCHAR(255) NOT NULL,
	  APhone INT NOT NULL,
	  ADiscount INT NOT NULL,
	  AID INT NOT NULL,
	  AEmail NVARCHAR(255) NOT NULL,
	  AFeePaid tinyint NOT NULL,
	  CID INT NOT NULL,
	  HName NVARCHAR(255) NOT NULL,
	  PRIMARY KEY (AID),
	  FOREIGN KEY (CID) REFERENCES CONFERENCE(CID),
	  FOREIGN KEY (HName) REFERENCES HOTEL(HName)
	);
